stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  CONTAINER_IMAGE: gitlab.sorewa.ru:5050/niaz/sport-plus-lct
build:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CONTAINER_IMAGE -f ./docker/dev.Dockerfile .
    - docker push $CONTAINER_IMAGE
  only:
    - main

deploy:
  stage: deploy
  script:
    - apk add --no-cache openssh sshpass
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
      cd /root/sport-plus-LCT &&
      export COMPOSE_PROJECT_NAME=sport-plus &&
      docker compose -f docker/dev.docker-compose.yml down &&
      git pull &&
      docker compose -f docker/dev.docker-compose.yml pull &&
      docker compose -f docker/dev.docker-compose.yml up -d &&
      docker system prune -f
      "
  only:
    - main