services:
  app:
    image: gitlab.sorewa.ru:5050/niaz/sport-plus-lct:latest
    build:
      context: ..
      dockerfile: docker/dev.Dockerfile
    # container_name: sport-plus-backend-1
    container_name: "${COMPOSE_PROJECT_NAME}_backend-1"
    env_file:
      - ../env/dev.env
    ports:
      - "8080:8000"
    restart: always
    networks:
      - sport-plus-network
    depends_on:
      - db

  db:
    image: postgres:13
    # container_name: sport-plus-postgres-db-1
    container_name: "${COMPOSE_PROJECT_NAME}_postgres-db-1"
    env_file:
      - ../env/dev.env
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./storage:/var/lib/postgresql/data
    networks:
      - sport-plus-network
  
  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
      - "8085:8080"
    depends_on:
      - db
    restart: always
    networks:
      - sport-plus-network
    env_file:
      - ../env/dev.env

networks:
  sport-plus-network:

volumes:
  postgres-db: