services:
  app:
    image: gitlab.sorewa.ru:5050/niaz/sport-plus-lct:latest
    build:
      context: ..
      dockerfile: docker/dev.Dockerfile
    container_name: sport-plus-backend-1
    env_file:
      - ../env/dev.env
    ports:
      - "8080:8000"
    networks:
      - sport-plus-network
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: sport-plus-postgres-db-1
    env_file:
      - ../env/dev.env
    ports:
      - "5432:5432"
    volumes:
      - ./storage:/var/lib/postgresql/data
    networks:
      - sport-plus-network

networks:
  sport-plus-network:

volumes:
  postgres-db: