version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/test.Dockerfile
    env_file:
      - ../env/test.dev
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - ../env/test.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: